spring:
  profiles:
    active: dev
  freemarker:
    template-loader-path: file:./templates/,classpath:templates/
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/jaylove
    username: root
    password: admin@123
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      validationQuery: SELECT 1
      filters: stat,wall
server:
  port: 8082
account:
  username: admin
  password: admin@123

jaylove:
  site:
    name: Love
    description: "Everything love"
    cdnUrl:

